stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - cd backend
    - cd worldwanderers 
    - ./gradlew build 
  # This job runs in the test stage.
backend-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cd backend
    - cd worldwanderers 
    - ./gradlew test
    - echo "Successfully passed tests"

deploy-job:
  stage: deploy 
  image: docker/compose:1.29.2  
  script:
    - cd backend
    - cd worldwanderers 
    - echo "Deploying the application..."
    - docker-compose up -d
  environment:
    name: production
  only:
    - main
