stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - cd backend
    - cd worldwanderers 
    - ./gradlew build -x test
    - echo "Completed building"
  # This job runs in the test stage.
backend-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - cd backend
    - cd worldwanderers 
    - ./gradlew test
    - echo "Successfully passed tests"
