version: 2.1
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew build
