version: 2.1
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew build

  test:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Run Tests with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew test

  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - docker/login:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - run:
          name: Log in to Docker Hub
          command: |
            echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
      - run:
          name: Build and Push Docker Image
          command: |
            cd backend/worldwanderers/post-service
            ./gradlew build
            docker build -t worldwanderers/post-service:v1.1 .
            docker push worldwanderers/post-service:v1.1

# Orchestrate the job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image

