version: 2.1
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew build

  test:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Run Tests with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew test

  build-image:
    docker:
      - image: musefys6/docker-gradle8-image:0.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u worldwanderers -p dckr_pat_iCd7KDdjcJJkoaIm3VZeJllxSuE
      - run:
          name: Build Docker Images
          command: |
            cd backend/worldwanderers/post-service
            ./gradlew build
            docker build -t worldwanderers/post-service:v1.1 .
            docker push worldwanderers/post-service:v1.1

            # cd ../group-service
            # ./gradlew build
            # docker build -t worldwanderers/group-service:v1.1 .

            # cd ../user-service
            # ./gradlew build
            # docker build -t worldwanderers/user-service:v1.1 .

            # cd ../security-service
            # ./gradlew build
            # docker build -t worldwanderers/security-service:v1.1 .

            # cd ../api-gateway
            # ./gradlew build
            # docker build -t worldwanderers/api-gateway:v1.1 .

            # cd ../discovery-service
            # ./gradlew build
            # docker build -t worldwanderers/discovery-service:v1.1 .

            echo "Build Docker images complete."

  push-image:
    docker:
      - image: musefys6/docker-gradle8-image:0.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u worldwanderers -p dckr_pat_iCd7KDdjcJJkoaIm3VZeJllxSuE
      - run:
          name: Push Docker Images to Docker Hub
          command: |
            # docker push worldwanderers/post-service:v1.1
            # docker push worldwanderers/group-service:v1.1
            # docker push worldwanderers/user-service:v1.1
            # docker push worldwanderers/security-service:v1.1
            # docker push worldwanderers/api-gateway:v1.1
            # docker push worldwanderers/discovery-service:v1.1
            echo "Push Docker images complete."

# Orchestrate the job run sequence
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-image:
          requires:
            - build
      - push-image:
          requires:
            - build-image
