version: 2.1
jobs:
  build:
    docker:
      - image: adoptopenjdk:17-jdk-hotspot
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew build
