version: 2.1
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Build with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew build

  test:
    docker:
      - image: azul/zulu-openjdk:17
    steps:
      - checkout
      - run:
          name: Run Tests with Gradle
          command: |
            cd backend/worldwanderers
            ./gradlew test

  build-push-images:
    docker:
      - image: musefys6/docker-gradle8-image:0.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u worldwanderers -p dckr_pat_iCd7KDdjcJJkoaIm3VZeJllxSuE
      - run:
          name: Build Docker Images
          command: |
            cd backend/worldwanderers/post-service
            ./gradlew build
            docker build -t worldwanderers/post-service:v1.1 .
            docker push worldwanderers/post-service:v1.1

            cd ../group-service
            ./gradlew build
            docker build -t worldwanderers/group-service:v1.1 .
            docker push worldwanderers/group-service:v1.1

            cd ../user-service
            ./gradlew build
            docker build -t worldwanderers/user-service:v1.1 .
            docker push worldwanderers/user-service:v1.1

            cd ../security-service
            ./gradlew build
            docker build -t worldwanderers/security-service:v1.1 .
            docker push worldwanderers/security-service:v1.1

            cd ../api-gateway
            ./gradlew build
            docker build -t worldwanderers/api-gateway:v1.1 .
            docker push worldwanderers/api-gateway:v1.1

            cd ../discovery-service
            ./gradlew build
            docker build -t worldwanderers/discovery-service:v1.1 .
            docker push worldwanderers/discovery-service:v1.1

            echo "Build Docker images complete."

  kubernetes-deployment:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Set up GCP credentials
          command: |
            echo "$SERVICE_ACCOUNT_KEY_BASE64" > service-account-key.json
            gcloud auth activate-service-account --key-file=service-account-key.json
            gcloud config set project avian-principle-382912
            gcloud container clusters get-credentials worldwanderers-deployment --region europe-west4 --project avian-principle-382912
      - run:
          name: Deploy to GCP
          command: |
            cd backend/worldwanderers/api-gateway
            echo "Apply deployment.yaml for api-gateway"
            kubectl apply -f deployment.yaml

            cd ../security-service
            echo "Apply deployment.yaml for security service"
            kubectl apply -f deployment.yaml

            cd ../user-service
            echo "Apply deployment.yaml for user service"
            kubectl apply -f deployment.yaml

            cd ../post-service
            echo "Apply deployment.yaml for post service"
            kubectl apply -f deployment.yaml

            cd ../group-service
            echo "Apply deployment.yaml for group service"
            kubectl apply -f deployment.yaml




# Orchestrate the job run sequence
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-push-images
      - kubernetes-deployment

