apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: worldwanderers/security-service:v1.1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker              
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: security-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
