version: '3'

services:
  discovery-service:
    image: worldwanderers/discovery-service:v1.1
    ports:
      - "8761:8761"

  api-gateway:
    image: worldwanderers/api-gateway-service:v1.1
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service

  group-service:
    image: worldwanderers/group-service:v1.1
    ports:
      - "8087:8087"
    depends_on:
      - api-gateway

  post-service:
    image: worldwanderers/post-service:v1.1
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway

  security-service:
    image: worldwanderers/security-service:v1.1
    ports:
      - "8082:8082"
    depends_on:
      - api-gateway
        
  user-service:
    image: worldwanderers/user-service:v1.1
    ports:
      - "8086:8086"
    depends_on:
      - api-gateway      