jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: |
        cd backend/worldwanderers
        ./gradlew build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Gradle
      run: |
        cd backend/worldwanderers
        ./gradlew test

  # build-docker-images:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1
  #   - name: Login to DockerHub
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #   - name: Build and push Docker images
  #     run: |
  #       cd backend/worldwanderers/post-service
  #       ./gradlew build
  #       docker build -t worldwanderers/post-service:v1.1 .
  #       docker push worldwanderers/post-service:v1.1
  #       # Repeat the above steps for all your services
